baseURL = 'https://github.com/cass4444/365-days-in-the-key-of-H/blob/main/static/'
languageCode = 'en-us'
title = '365 Days in the Key of H Major'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3